# Generated by Django 2.0.3 on 2018-04-01 14:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0027_auto_20180401_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.User')),
            ],
            options={
                'verbose_name': 'Online Status',
                'verbose_name_plural': 'Online Status',
                'ordering': ['-last_login'],
            },
        ),
    ]
